### ISSUE TITLE
As a user I want to be able to adjust parameters of the game, in order to customize my experience

### ISSUE THREAD

**Issue by marcoleder** [sopra-fs22-group-17/RaveWave-client#87]
As a user I want to be able to adjust parameters of the game, in order to customize my experience.

Development tasks:
- [x] #88
- [x] #89
- [x] #90
- [x] #97

Acceptance criteria:
- [ ] The user can adjust game parameters via sliders and buttons in a visual pleasing way
- [ ] Direct feedback about which parameters are currently selected shall be implicitly given
- [ ] Any adjustments after having confirmed the parameters shall be ignored

**Comment by SheenaGit** [comment]
solved in 6e2fbcb1217e3f7c2bb1d375ad346fb44a50efd0
